Add deployment event calls to GitHub
The deployment status event can then be consumed by GitHub's Slack app
to post notifications on the status of deploys, triggered by commit pushes or
Contentful changes.

I used these docs: https://developer.github.com/v3/repos/deployments/

diff --git a/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2 b/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
--- a/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
+++ b/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
@@ -5,14 +5,58 @@
 set -efuo pipefail
 IFS=$'\n\t'
 
+GITHUB_USER="svsticky-deploy"
+GITHUB_PASSWORD="{{ secret_static_sticky.github_deployments_token }}"
+DEPLOY_ENV="{{ ('staging' in group_names) | ternary("staging", "production") }}"
+
+fail_github_deploy_status() {
+  # Create a "deployment status" at GitHub: "failure"
+  curl \
+    --silent --show-error \
+    --output /dev/null \
+    --fail \
+    --user "${GITHUB_USER}:${GITHUB_PASSWORD}" \
+    --header "Accept: application/vnd.github.v3+json" \
+    --header "Content-Type: application/json" \
+    --request POST \
+    --data '{"state": "failure"}' \
+    "https://api.github.com/repos/svsticky/static-sticky/deployments/${DEPLOY_ID}/statuses"
+}
+
 cd /var/www/static-sticky/static-sticky
 
 git reset --hard HEAD
 
-PREV_GIT_REF="$(git rev-parse HEAD)"
+PREV_GIT_REF="$(git rev-parse --short HEAD)"
 # Get latest version of website sourcecode
 git pull origin {{ static_sticky_env.git_ref }}
-NEW_GIT_REF="$(git rev-parse HEAD)"
+NEW_GIT_REF="$(git rev-parse --short HEAD)"
+
+if [[ "${PREV_GIT_REF}" != "${NEW_GIT_REF}" ]]; then
+  DEPLOY_DESCRIPTION="Deploying commit ${NEW_GIT_REF} on top of ${OLD_GIT_REF}."
+else
+  DEPLOY_DESCRIPTION="Deploying new changes from Contentful."
+fi
+
+# Create a "deployment" at GitHub and save its ID
+DEPLOY_ID="$(curl \
+  --silent --show-error \
+  --fail \
+  --user "${GITHUB_USER}:${GITHUB_PASSWORD}" \
+  --header "Accept: application/vnd.github.v3+json" \
+  --header "Content-Type: application/json" \
+  --request POST \
+  --data \
+    '{"ref": "'"${NEW_GIT_REF}"'",
+      "auto_merge": false,
+      "required_context": [],
+      "description": "'"${DEPLOY_DESCRIPTION}"'",
+      "environment": "'"${DEPLOY_ENV}"'"
+    }' \
+  https://api.github.com/repos/svsticky/static-sticky/deployments \
+  | jq --raw-output '.id')"
+
+trap fail_github_deploy_status ERR
 
 source /var/www/static-sticky/.nvm/nvm.sh
 
@@ -28,5 +72,17 @@ npm run build
 
 # Copy website contents to webroot, replacing already existing target contents
 rsync --delete --recursive \
-    /var/www/static-sticky/static-sticky/public/ \
-    /var/www/static-sticky/static.{{ canonical_hostname }}/
+  /var/www/static-sticky/static-sticky/public/ \
+  /var/www/static-sticky/static.{{ canonical_hostname }}/
+
+# Create a "deployment status" at GitHub: "success"
+curl \
+  --silent --show-error \
+  --output /dev/null \
+  --fail \
+  --user "${GITHUB_USER}:${GITHUB_PASSWORD}" \
+  --header "Accept: application/vnd.github.v3+json" \
+  --header "Content-Type: application/json" \
+  --request POST \
+  --data '{"state": "success"}' \
+  "https://api.github.com/repos/svsticky/static-sticky/deployments/${DEPLOY_ID}/statuses"
