Purge build cache and retry if website build fails
Kind of ugly hotfix for #217, so leaving that open.

diff --git a/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2 b/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
--- a/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
+++ b/ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
@@ -71,8 +71,8 @@ if [[ "${PREV_GIT_REF}" != "${NEW_GIT_REF}" ]]; then
   npm install
 fi
 
-# Build website
-npm run build
+# Build website, and if it fails retry after purging the local cache
+npm run build || { rm -r ./.cache && npm run build; }
 
 # Copy website contents to webroot, replacing already existing target contents
 rsync --delete --recursive \
